version: '3.8'
services:
  db1:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application1
      - MYSQL_PASSWORD=application1
      - MYSQL_DATABASE=concert
    volumes:
      - ./data/mysql1/:/var/lib/mysql

  db2:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application2
      - MYSQL_PASSWORD=application2
      - MYSQL_DATABASE=concert2
    volumes:
      - ./data/mysql2/:/var/lib/mysql

networks:
  default:
    driver: bridge