version: '3'
services:
  mysql:
    image: mariadb:11.6.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=concert
    volumes:
      - ./data/mysql/:/var/lib/mysql

  redis:
    image: redis:7.4.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - concert-network

networks:
  default:
    driver: bridge